# Generated by Django 5.0.2 on 2024-03-06 11:50

import buds.models
import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to=buds.models.getFileName)),
                ('category_description', models.TextField(max_length=500)),
                ('category_status', models.BooleanField(default=False, help_text='0-Show,1-Hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=buds.models.getFileName)),
                ('Product_description', models.TextField(max_length=500)),
                ('postimage', models.ImageField(upload_to=buds.models.getFileName)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=5, null=True)),
                ('product_boxitems', models.CharField(blank=True, max_length=255, null=True)),
                ('product_warrenty', models.CharField(blank=True, max_length=255, null=True)),
                ('product_playtime', models.CharField(blank=True, max_length=255, null=True)),
                ('product_waterresistent', models.CharField(blank=True, max_length=255, null=True)),
                ('product_fastcharging', models.CharField(blank=True, max_length=255, null=True)),
                ('product_buildquality', models.CharField(blank=True, max_length=255, null=True)),
                ('product_colours', models.CharField(blank=True, max_length=255, null=True)),
                ('product_mic', models.CharField(blank=True, max_length=255, null=True)),
                ('product_bass_rating', models.IntegerField(blank=True, null=True)),
                ('product_build_quality_rating', models.IntegerField(blank=True, null=True)),
                ('product_bluetooth_connectivity_rating', models.IntegerField(blank=True, null=True)),
                ('louderbud_rating', models.IntegerField(blank=True, null=True)),
                ('bestbuy', models.BooleanField(default=False)),
                ('latest', models.BooleanField(default=False)),
                ('trending', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Product_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buds.brand')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('catregory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buds.category')),
            ],
        ),
    ]
