# Generated by Django 5.0.2 on 2024-03-06 12:20

import buds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comparision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product1_name', models.CharField(blank=True, max_length=50, null=True)),
                ('product1_image', models.ImageField(blank=True, null=True, upload_to=buds.models.getFileName)),
                ('product1_price', models.IntegerField(blank=True, null=True)),
                ('product1_boxitems', models.CharField(blank=True, max_length=255, null=True)),
                ('product1_warrenty', models.CharField(blank=True, max_length=255, null=True)),
                ('product1_playtime', models.CharField(blank=True, max_length=255, null=True)),
                ('product1_waterresistent', models.CharField(blank=True, max_length=255, null=True)),
                ('product1_fastcharging', models.CharField(blank=True, max_length=255, null=True)),
                ('product1_buildquality', models.CharField(blank=True, max_length=255, null=True)),
                ('product1_colours', models.CharField(blank=True, max_length=255, null=True)),
                ('product1_mic', models.CharField(blank=True, max_length=255, null=True)),
                ('product1_bass_rating', models.IntegerField(blank=True, null=True)),
                ('product1_build_quality_rating', models.IntegerField(blank=True, null=True)),
                ('product1_bluetooth_connectivity_rating', models.IntegerField(blank=True, null=True)),
                ('product2_name', models.CharField(blank=True, max_length=50, null=True)),
                ('product2_image', models.ImageField(blank=True, null=True, upload_to=buds.models.getFileName)),
                ('product2_price', models.IntegerField(blank=True, null=True)),
                ('product2_boxitems', models.CharField(blank=True, max_length=255, null=True)),
                ('product2_warrenty', models.CharField(blank=True, max_length=255, null=True)),
                ('product2_playtime', models.CharField(blank=True, max_length=255, null=True)),
                ('product2_waterresistent', models.CharField(blank=True, max_length=255, null=True)),
                ('product2_fastcharging', models.CharField(blank=True, max_length=255, null=True)),
                ('product2_buildquality', models.CharField(blank=True, max_length=255, null=True)),
                ('product2_colours', models.CharField(blank=True, max_length=255, null=True)),
                ('product2_mic', models.CharField(blank=True, max_length=255, null=True)),
                ('product2_bass_rating', models.IntegerField(blank=True, null=True)),
                ('product2_build_quality_rating', models.IntegerField(blank=True, null=True)),
                ('product2_bluetooth_connectivity_rating', models.IntegerField(blank=True, null=True)),
                ('louderbud_rating', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
