# Generated by Django 5.0.2 on 2024-03-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buds', '0002_comparision'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparision',
            name='comparision_post_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
