# Generated by Django 5.0.2 on 2024-03-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buds', '0003_comparision_comparision_post_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparision',
            name='product1_bass_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comparision',
            name='product1_bluetooth_connectivity_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comparision',
            name='product1_build_quality_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_article',
            name='louderbud_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
