# Generated by Django 5.0.2 on 2024-03-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buds', '0004_alter_comparision_product1_bass_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparision',
            name='louderbud_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comparision',
            name='product2_bass_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comparision',
            name='product2_bluetooth_connectivity_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comparision',
            name='product2_build_quality_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_article',
            name='product_bass_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_article',
            name='product_bluetooth_connectivity_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_article',
            name='product_build_quality_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
