# Generated by Django 5.0.2 on 2024-03-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buds', '0005_alter_comparision_louderbud_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comparision',
            old_name='louderbud_rating',
            new_name='product1_louderbud_rating',
        ),
        migrations.AddField(
            model_name='comparision',
            name='product2_louderbud_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
